services:

  mysql-server:
    image: mysql:8.0.42
    environment:
      MYSQL_ROOT_PASSWORD: asd123
    ports:
      - 3306:3306
    container_name: mysql-server
    volumes:
      - ./mysql_data:/var/lib/mysql
